Flag --generator has been deprecated, has no effect and will be removed in the future.
Error from server (AlreadyExists): pods "mlmapi20210117" already exists
NAME             READY   STATUS    RESTARTS   AGE
mlmapi20210117   1/1     Running   0          5m3s
Forwarding from 127.0.0.1:8000 -> 80
Forwarding from [::1]:8000 -> 80
Handling connection for 8000
 * Serving Flask app "app" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on http://0.0.0.0:80/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 300-388-788
 * Detected change in '/usr/local/lib/python3.7/site-packages/pytz/__init__.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 300-388-788
[2021-01-18 01:52:03,381] INFO in app: JSON payload:
{'CHAS': {'0': 0}, 'RM': {'0': 6.575}, 'TAX': {'0': 296.0}, 'PTRATIO': {'0': 15.3}, 'B': {'0': 396.9}, 'LSTAT': {'0': 4.98}}
[2021-01-18 01:52:03,921] INFO in app: Inference payload DataFrame:
   CHAS     RM    TAX  PTRATIO      B  LSTAT
0     0  6.575  296.0     15.3  396.9   4.98
[2021-01-18 01:52:03,942] INFO in app: Scaling Payload:
   CHAS     RM    TAX  PTRATIO      B  LSTAT
0     0  6.575  296.0     15.3  396.9   4.98
[2021-01-18 01:52:04,032] INFO in app: Prediction value:
[20.35373177134412]
127.0.0.1 - - [18/Jan/2021 01:52:04] "POST /predict HTTP/1.1" 200 -